// Scene template: static multicolor bitmap from gfx.py + a one-IRQ frame loop.
// Add raster effects by chaining more IRQs with HX_NextIrq (see scenes/testcard/main.asm).
#import "harness.asm"
#import "gfx.asm"                   // generated by gfx.py

HX_Header(start, "template", 0)     // flags: 0 = PAL, HX_FLAG_NTSC = NTSC
HX_VicShadow(Hashtable().put(
    $d011, $3b,                     // bitmap mode, display on, 25 rows, yscroll 3
    $d016, $18,                     // multicolor, 40 columns
    $d018, GFX_D018,
    $d020, GFX_BORDER,
    $d021, GFX_BG))

.segment ColorRam
    .import binary "colorram.bin"
.segment Bank
    .import binary "bank.bin"

.segment Code
start:
    HX_Init()                       // VIC regs + color RAM from the image, bank 1, ROMs off
    HX_StartIrq(frame_irq, $fa)
    HX_SignalReady()
    jmp *

frame_irq:                          // once per frame, in the lower border
    HX_IrqEnter()
    HX_FrameTick()
    HX_IrqExit()
